### ISSUE TITLE
Gathering Luck missing the Herbs node

### ISSUE THREAD

**Issue by jkantr** [meissnereric/BraveNW#26]
Is this an oversight, or is there some specific trouble with trying to calculate herb chances? Nodes could be broken down by region they are in (since the results change by region).

**Comment by meissnereric** [comment]
Yeah I didn't include herb chance because this was a sort of, first pass for things and herbs were a bit more complex with the zone calculations. For now, here are the luck values it produces (so small has 50% chance, medium 57.5%, large 65% by default with no luck). Should be easy enough to add, just a little work.

![image](https://user-images.githubusercontent.com/6857699/135772981-9f80578a-330d-49ee-8ff0-7bc1cae2307a.png)

**Comment by jkantr** [comment]
This is fantastic, thank you for the reply.

The only confusing thing about this is you can generally get more than 1 "rare" type of herb from an herb by region... so it's unclear how they use these rules. For instance, cinnamon in LF seems to be "most rare", where some patches only give hyssop, some thyme (or mint?), and some (the least) cinnamon. It's definitely (significantly) lower than 50% also. Like.. i dunno, 5-10% maybe anecdotally.

**Comment by meissnereric** [comment]
Sorry I missed this comment, I don't really have any more information on that. I expect that they are randomly selected from the list of possible herbs for that region, and that's mostly what I've found when harvesting. If I gather a few thousand hyssop, I generally come back to town with equal-ish stacks of the other herbs.

Also this should be properly added to the site now! :)
